// mockEventData.js

const eventData = [
    {
      id: 1,
      title: 'Tech Conference 2024',
      date: '10th March 2024',
      location: 'SRM University, Chennai',
      description: 'A premier gathering of tech enthusiasts, startups, and industry leaders.',
      image: require('../assets/images/events/event1.png'),
      bannerImage: require('../assets/images/events/event1.png'),
      logoImage: require('../assets/images/events/eventLogo1.png'),
      organizer: 'TechWorld Association',
      sponsors: ['Google', 'Microsoft'],
      mode: 'Offline',
      startDate: '2024-03-10',
      endDate: '2024-03-12',
      participationCriteria: 'Open to all tech professionals and enthusiasts.',
      schedule: [
        { time: '9:00 AM', activity: 'Registration & Welcome' },
        { time: '10:00 AM', activity: 'Keynote Speech' },
        { time: '12:00 PM', activity: 'Panel Discussion' },
        { time: '2:00 PM', activity: 'Networking Session' },
        { time: '4:00 PM', activity: 'Workshops' },
      ],
      contactEmail: 'contact@techconference.com',
      contactPhone: '+123456789',
    },
    {
      id: 2,
      title: 'Startup Pitch Fest',
      date: '5th April 2024',
      location: 'SRM University, Chennai',
      description: 'A platform for entrepreneurs to pitch their ideas to investors and mentors.',
      image: require('../assets/images/events/event2.png'),
      bannerImage: require('../assets/images/events/event2.png'),
      logoImage: require('../assets/images/events/eventLogo2.png'),
      organizer: 'Entrepreneurship Network',
      sponsors: ['Sequoia Capital', 'Y Combinator'],
      mode: 'Offline',
      startDate: '2024-04-05',
      endDate: '2024-04-06',
      participationCriteria: 'Open to startups and aspiring entrepreneurs.',
      schedule: [
        { time: '10:00 AM', activity: 'Opening Ceremony' },
        { time: '11:30 AM', activity: 'Startup Pitches' },
        { time: '3:00 PM', activity: 'Mentorship Sessions' },
        { time: '5:00 PM', activity: 'Networking & Closing' },
      ],
      contactEmail: 'info@pitchfest.com',
      contactPhone: '+987654321',
    },
    {
      id: 3,
      title: 'AI & Machine Learning Summit',
      date: '15th May 2024',
      location: 'Online',
      description: 'Exploring the latest advancements in artificial intelligence and machine learning.',
      image: require('../assets/images/events/event3.png'),
      bannerImage: require('../assets/images/events/event3.png'),
      logoImage: require('../assets/images/events/eventLogo3.png'),
      organizer: 'AI Research Society',
      sponsors: ['OpenAI', 'NVIDIA'],
      mode: 'Online',
      startDate: '2024-05-15',
      endDate: '2024-05-16',
      participationCriteria: 'Open to AI researchers, professionals, and students.',
      schedule: [
        { time: '9:30 AM', activity: 'Check-In' },
        { time: '10:30 AM', activity: 'Research Presentations' },
        { time: '1:00 PM', activity: 'Panel Discussion' },
        { time: '3:30 PM', activity: 'Networking & Closing' },
      ],
      contactEmail: 'support@aisummit.com',
      contactPhone: '+1122334455',
    },
    {
      id: 4,
      title: 'Cultural Fest 2024',
      date: '20th June 2024',
      location: 'SRM University, Chennai',
      description: 'A vibrant celebration of art, music, and dance.',
      image: require('../assets/images/events/event4.png'),
      bannerImage: require('../assets/images/events/event4.png'),
      logoImage: require('../assets/images/events/eventLogo4.png'),
      organizer: 'SRM Cultural Club',
      sponsors: ['Red Bull', 'MTV'],
      mode: 'Offline',
      startDate: '2024-06-20',
      endDate: '2024-06-22',
      participationCriteria: 'Open to all students and performers.',
      schedule: [
        { time: '10:00 AM', activity: 'Opening Ceremony' },
        { time: '11:30 AM', activity: 'Dance Performances' },
        { time: '3:00 PM', activity: 'Music Concert' },
      ],
      contactEmail: 'culture@srmfest.com',
      contactPhone: '+9988776655',
    },
    {
      id: 5,
      title: 'Online Photography Contest',
      date: '10th July 2024',
      location: 'Online',
      description: 'A global competition for aspiring photographers to showcase their talent.',
      image: require('../assets/images/events/event5.png'),
      bannerImage: require('../assets/images/events/event5.png'),
      logoImage: require('../assets/images/events/eventLogo5.png'),
      organizer: 'SRM Media Club',
      sponsors: ['Canon', 'Adobe'],
      mode: 'Online',
      startDate: '2024-07-10',
      endDate: '2024-07-20',
      participationCriteria: 'Open to all photography enthusiasts.',
      schedule: [
        { time: '12:00 AM', activity: 'Submission Opens' },
        { time: '11:59 PM', activity: 'Submission Closes' },
      ],
      contactEmail: 'photography@srmmedia.com',
      contactPhone: '+5566778899',
    },
    {
      id: 6,
      title: 'Health & Wellness Expo',
      date: '5th August 2024',
      location: 'SRM University, Chennai',
      description: 'A platform to explore health, fitness, and mental wellness.',
      image: require('../assets/images/events/event6.png'),
      bannerImage: require('../assets/images/events/event6.png'),
      logoImage: require('../assets/images/events/eventLogo6.png'),
      organizer: 'SRM Health Club',
      sponsors: ['Nike', 'Herbalife'],
      mode: 'Offline',
      startDate: '2024-08-05',
      endDate: '2024-08-06',
      participationCriteria: 'Open to all health-conscious individuals.',
      schedule: [
        { time: '9:00 AM', activity: 'Yoga & Meditation' },
        { time: '11:00 AM', activity: 'Healthy Cooking Workshop' },
        { time: '2:00 PM', activity: 'Fitness Challenge' },
      ],
      contactEmail: 'wellness@srmhealth.com',
      contactPhone: '+3344556677',
    },
  ];
  
  export default eventData;
  
  export { eventData };
  