const FindPartnerData = [
    {
      id: 1,
      title: 'AI-Powered Resume Analyzer',
      projectType: 'Hackathon',
      organizedBy: 'Alex Johnson',
      datePosted: '5th February 2024',
      location: 'Remote',
      description: 'Join our hackathon team to develop an AI-based resume analyzer that helps job seekers get instant feedback on their resumes.',
      image: require('../assets/images/FindPartner/Partner1.png'),
      skillsRequired: ['Python', 'Machine Learning', 'NLP'],
      lookingFor: ['AI Engineer', 'Backend Developer', 'UI/UX Designer'],
      teamSize: '4-6 members',
      duration: '48-hour hackathon',
      contactInformation: {
        email: 'alex.johnson@collab.com',
        phone: '+1-555-6789-001',
      },
    },
    {
      id: 2,
      title: 'Climate Change Data Analysis',
      projectType: 'Research',
      organizedBy: 'Sophia Martinez',
      datePosted: '10th February 2024',
      location: 'University Collaboration (Hybrid)',
      description: 'Seeking researchers to analyze global climate data and develop AI models for predicting future temperature trends.',
      image: require('../assets/images/FindPartner/Partner2.png'),
      skillsRequired: ['Data Science', 'Python', 'TensorFlow', 'GIS Mapping'],
      lookingFor: ['Data Analyst', 'Research Scientist', 'AI Developer'],
      teamSize: '3-5 members',
      duration: '3 months',
      contactInformation: {
        email: 'sophia.martinez@research.com',
        phone: '+1-555-6789-002',
      },
    },
    {
      id: 3,
      title: 'Startup Landing Page Development',
      projectType: 'Website Project',
      organizedBy: 'James Carter',
      datePosted: '15th February 2024',
      location: 'Remote',
      description: 'Looking for a web developer and UI/UX designer to create a landing page for our startup focused on ed-tech solutions.',
      image: require('../assets/images/FindPartner/Partner3.png'),
      skillsRequired: ['React', 'Tailwind CSS', 'Next.js'],
      lookingFor: ['Frontend Developer', 'UI/UX Designer'],
      teamSize: '2-3 members',
      duration: '2 weeks',
      contactInformation: {
        email: 'james.carter@startup.com',
        phone: '+1-555-6789-003',
      },
    },
    {
      id: 4,
      title: 'Blockchain-Based Voting System',
      projectType: 'Research & Development',
      organizedBy: 'Olivia Brown',
      datePosted: '20th February 2024',
      location: 'Remote',
      description: 'Building a secure blockchain-based e-voting system. Looking for developers and blockchain researchers to join the project.',
      image: require('../assets/images/FindPartner/Partner4.png'),
      skillsRequired: ['Blockchain', 'Solidity', 'Hyperledger'],
      lookingFor: ['Blockchain Developer', 'Cryptography Expert', 'Smart Contract Engineer'],
      teamSize: '5-7 members',
      duration: '6 months',
      contactInformation: {
        email: 'olivia.brown@blockchain.com',
        phone: '+1-555-6789-004',
      },
    },
    {
      id: 5,
      title: 'Mental Health Chatbot for Students',
      projectType: 'Hackathon',
      organizedBy: 'Daniel Wilson',
      datePosted: '25th February 2024',
      location: 'Onsite (New York)',
      description: 'Join our hackathon team to develop an AI chatbot that helps students manage stress and mental health through guided conversations.',
      image: require('../assets/images/FindPartner/Partner5.png'),
      skillsRequired: ['AI Chatbots', 'NLP', 'Python', 'React'],
      lookingFor: ['AI Engineer', 'Frontend Developer', 'Psychology Researcher'],
      teamSize: '3-5 members',
      duration: '72-hour hackathon',
      contactInformation: {
        email: 'daniel.wilson@event.com',
        phone: '+1-555-6789-005',
      },
    },
    {
      id: 6,
      title: 'E-Commerce Platform for Local Artists',
      projectType: 'Website Project',
      organizedBy: 'Emma Thompson',
      datePosted: '1st March 2024',
      location: 'Remote',
      description: 'We are building an e-commerce platform that allows local artists to sell their handmade crafts. Looking for developers and designers.',
      image: require('../assets/images/FindPartner/Partner6.png'),
      skillsRequired: ['React', 'Node.js', 'MongoDB', 'Stripe API'],
      lookingFor: ['Full-Stack Developer', 'UI/UX Designer'],
      teamSize: '3-4 members',
      duration: '1 month',
      contactInformation: {
        email: 'emma.thompson@startup.com',
        phone: '+1-555-6789-006',
      },
    },
  ];
  
  export default FindPartnerData;
  export { FindPartnerData };
  