// mockData.js

const hackathonData = [
  {
    id: 1,
    title: 'Blockchain Hackathon',
    date: '15th January 2024',
    location: 'Innovation Hub, TP Ganesan Auditorium',
    description: 'Showcase your blockchain development skills and win exciting prizes.',
    image: require('../assets/images/landingPage/hackathon1.png'),
    bannerImage: require('../assets/images/landingPage/hackathon1.png'),
    logoImage: require('../assets/images/landingPage/hackathonLogo1.png'),
    organizer: 'Tech Innovation Society',
    sponsors: ['IBM', 'Microsoft'],
    mode: 'Offline',
    startDate: '2024-01-15',
    endDate: '2024-01-16',
    participationCriteria: 'Open to students, professionals, and enthusiasts with knowledge of blockchain.',
    schedule: [
      { time: '9:00 AM', activity: 'Registration' },
      { time: '10:00 AM', activity: 'Keynote Speech' },
      { time: '11:00 AM', activity: 'Hackathon Begins' },
      { time: '5:00 PM', activity: 'Day 1 Ends' },
      { time: '9:00 AM', activity: 'Day 2 Begins' },
      { time: '3:00 PM', activity: 'Submission Deadline' },
      { time: '5:00 PM', activity: 'Winner Announcement' },
    ],
    rules: ['Teams of up to 4 members', 'Code must be original and developed during the hackathon'],
    prizeDetails: [
      { place: '1st', prize: '$5000' },
      { place: '2nd', prize: '$3000' },
      { place: '3rd', prize: '$1000' },
    ],
    contactEmail: 'contact@blockchainhack.com',
    contactPhone: '+123456789',
  },
  {
    id: 2,
    title: 'AI-Powered Solutions',
    date: '20th February 2024',
    location: 'Main Auditorium',
    description: 'Develop AI-based innovative solutions to real-world problems.',
    image: require('../assets/images/landingPage/hackathon2.png'),
    bannerImage: require('../assets/images/landingPage/hackathon2.png'),
    logoImage: require('../assets/images/landingPage/hackathonLogo2.png'),
    organizer: 'AI Innovators Club',
    sponsors: ['Google', 'Intel'],
    mode: 'Offline',
    startDate: '2024-02-20',
    endDate: '2024-02-21',
    participationCriteria: 'Open to anyone with knowledge of AI or machine learning.',
    schedule: [
      { time: '8:30 AM', activity: 'Check-In' },
      { time: '9:30 AM', activity: 'Welcome Speech' },
      { time: '10:00 AM', activity: 'Hackathon Kickoff' },
      { time: '5:30 PM', activity: 'Networking Session' },
      { time: '9:00 AM', activity: 'Day 2 Continues' },
      { time: '1:00 PM', activity: 'Project Presentation' },
      { time: '4:00 PM', activity: 'Awards Ceremony' },
    ],
    rules: ['No pre-developed code allowed', 'Participants must follow ethical guidelines'],
    prizeDetails: [
      { place: '1st', prize: '$7000' },
      { place: '2nd', prize: '$4000' },
      { place: '3rd', prize: '$2000' },
    ],
    contactEmail: 'support@aihacks.com',
    contactPhone: '+987654321',
  },
  {
    id: 3,
    title: 'Web 3.0 Builders',
    date: '5th March 2024',
    location: 'Online',
    description: 'Collaborate and create decentralized applications in Web 3.0.',
    image: require('../assets/images/landingPage/hackathon3.png'),
    bannerImage: require('../assets/images/landingPage/hackathon3.png'),
    logoImage: require('../assets/images/landingPage/hackathonLogo3.png'),
    organizer: 'Decentralized Developers Guild',
    sponsors: ['ConsenSys', 'AWS'],
    mode: 'Online',
    startDate: '2024-03-05',
    endDate: '2024-03-07',
    participationCriteria: 'Familiarity with blockchain and decentralized apps required.',
    schedule: [
      { time: '10:00 AM', activity: 'Opening Ceremony' },
      { time: '11:00 AM', activity: 'Hackathon Start' },
      { time: '6:00 PM', activity: 'Team Collaboration Session' },
      { time: '10:00 AM', activity: 'Day 2 Begins' },
      { time: '4:00 PM', activity: 'Mid-Project Checkpoint' },
      { time: '3:00 PM', activity: 'Final Submission' },
      { time: '5:00 PM', activity: 'Winners Announcement' },
    ],
    rules: ['Teams must be 100% virtual', 'Submissions must use blockchain technology'],
    prizeDetails: [
      { place: '1st', prize: '$8000' },
      { place: '2nd', prize: '$5000' },
      { place: '3rd', prize: '$3000' },
    ],
    contactEmail: 'info@web3builders.com',
    contactPhone: '+1122334455',
  },
  {
    id: 4,
    title: 'Cybersecurity Challenge',
    date: '25th March 2024',
    location: 'Tech Lab 2',
    description: 'Compete in solving cybersecurity challenges and improve your skills.',
    image: require('../assets/images/landingPage/hackathon4.png'),
    bannerImage: require('../assets/images/landingPage/hackathon4.png'),
    logoImage: require('../assets/images/landingPage/hackathonLogo4.png'),
    organizer: 'Cyber Warriors Association',
    sponsors: ['Palo Alto Networks', 'Cisco'],
    mode: 'Offline',
    startDate: '2024-03-25',
    endDate: '2024-03-26',
    participationCriteria: 'Knowledge of cybersecurity and ethical hacking preferred.',
    schedule: [
      { time: '8:00 AM', activity: 'Check-In' },
      { time: '9:00 AM', activity: 'Cybersecurity Workshop' },
      { time: '11:00 AM', activity: 'Hackathon Commencement' },
      { time: '5:00 PM', activity: 'Day 1 Wrap-Up' },
      { time: '8:00 AM', activity: 'Day 2 Challenges Begin' },
      { time: '2:00 PM', activity: 'Submission Deadline' },
      { time: '3:30 PM', activity: 'Prize Distribution' },
    ],
    rules: ['Strictly no sharing of sensitive data', 'Follow ethical hacking practices'],
    prizeDetails: [
      { place: '1st', prize: '$6000' },
      { place: '2nd', prize: '$4000' },
      { place: '3rd', prize: '$2000' },
    ],
    contactEmail: 'cyberhack@challenges.com',
    contactPhone: '+6677889900',
  },
  {
    id: 5,
    title: 'IoT Innovation Hackathon',
    date: '10th April 2024',
    location: 'Tech Park, Mini Hall 1',
    description: 'Create IoT-based innovative solutions to modern challenges.',
    image: require('../assets/images/landingPage/hackathon5.png'),
    bannerImage: require('../assets/images/landingPage/hackathon5.png'),
    logoImage: require('../assets/images/landingPage/hackathonLogo5.png'),
    organizer: 'IoT Creators Network',
    sponsors: ['Cisco', 'Intel'],
    mode: 'Offline',
    startDate: '2024-04-10',
    endDate: '2024-04-11',
    participationCriteria: 'Open to engineers, developers, and IoT enthusiasts.',
    schedule: [
      { time: '9:00 AM', activity: 'Registration and Welcome' },
      { time: '10:30 AM', activity: 'Keynote Session' },
      { time: '11:30 AM', activity: 'Hackathon Start' },
      { time: '5:00 PM', activity: 'Day 1 Closing' },
      { time: '9:00 AM', activity: 'Day 2 Opening' },
      { time: '2:00 PM', activity: 'Project Demos' },
      { time: '4:00 PM', activity: 'Winner Announcement and Closing' },
    ],
    rules: ['Teams can have up to 5 members', 'Projects must integrate IoT technology'],
    prizeDetails: [
      { place: '1st', prize: '$7000' },
      { place: '2nd', prize: '$4000' },
      { place: '3rd', prize: '$2000' },
    ],
    contactEmail: 'contact@iotinnovations.com',
    contactPhone: '+4455667788',
  },
  {
    id: 6,
    title: 'Sustainable Tech Hackathon',
    date: '30th April 2024',
    location: 'Main Auditorium',
    description: 'Develop technologies to promote sustainability and eco-friendliness.',
    image: require('../assets/images/landingPage/hackathon6.png'),
    bannerImage: require('../assets/images/landingPage/hackathon6.png'),
    logoImage: require('../assets/images/landingPage/hackathonLogo6.png'),
    organizer: 'GreenTech Society',
    sponsors: ['Tesla', 'Google'],
    mode: 'Offline',
    startDate: '2024-04-30',
    endDate: '2024-05-01',
    participationCriteria: 'Innovators and professionals passionate about sustainability.',
    schedule: [
      { time: '8:30 AM', activity: 'Registration and Breakfast' },
      { time: '9:30 AM', activity: 'Opening Remarks' },
      { time: '10:00 AM', activity: 'Hackathon Launch' },
      { time: '5:00 PM', activity: 'Day 1 Wrap-Up' },
      { time: '9:00 AM', activity: 'Day 2 Resume' },
      { time: '1:00 PM', activity: 'Final Presentations' },
      { time: '3:30 PM', activity: 'Awards Ceremony' },
    ],
    rules: ['Solutions must address sustainability challenges', 'Projects should be implementable'],
    prizeDetails: [
      { place: '1st', prize: '$10,000' },
      { place: '2nd', prize: '$5000' },
      { place: '3rd', prize: '$3000' },
    ],
    contactEmail: 'sustainable@techteam.com',
    contactPhone: '+9988776655',
  },
];

export default hackathonData;


  const projectData = [
    {
      id: 1,
      title: 'Blockchain Solutions with IBM',
      date: '15th January 2024',
      location: 'Innovation Hub, TP Ganesan Auditorium',
      description: 'Collaborate with IBM to develop blockchain-based solutions for real-world problems.',
      image: require('../assets/images/landingPage/projectimg1.png'),
    },
    {
      id: 2,
      title: 'AI Innovations with Google',
      date: '20th February 2024',
      location: 'Main Auditorium',
      description: 'Work alongside Google experts to create AI-powered innovative solutions.',
      image: require('../assets/images/landingPage/projectimg2.png'),
    },
    {
      id: 3,
      title: 'Web 3.0 Projects with ConsenSys',
      date: '5th March 2024',
      location: 'Online',
      description: 'Join ConsenSys in building next-generation decentralized Web 3.0 applications.',
      image: require('../assets/images/landingPage/projectimg3.png'),
    },
    {
      id: 4,
      title: 'Cybersecurity Projects with Amazon',
      date: '25th March 2024',
      location: 'Tech Lab 2',
      description: 'Solve advanced cybersecurity challenges with experts from Palo Alto Networks.',
      image: require('../assets/images/landingPage/projectimg4.png'),
    },
    {
      id: 5,
      title: 'IoT Innovations with Cisco',
      date: '10th April 2024',
      location: 'Tech Park, Mini Hall 1',
      description: 'Collaborate with Cisco on IoT projects addressing modern connectivity challenges.',
      image: require('../assets/images/landingPage/projectimg5.png'),
    },
    {
      id: 6,
      title: 'Sustainable Tech Projects with Tesla',
      date: '30th April 2024',
      location: 'Main Auditorium',
      description: 'Join Tesla in creating sustainable and eco-friendly technological solutions.',
      image: require('../assets/images/landingPage/projectimg6.png'),
    },
  ];
  
  export { hackathonData, projectData };
  